from enum import Enum

class Datafromat(Enum):
    VESC_motor_driver = [
    "Datalogger port",
    "Dataloggertijd, in s",
    "Format header",
    "Tijd sinds boot, in s",
    "Ingangsspanning meetsysteem, in V",
    "Temperatuur meetsysteem, in graden Celsius",
    "Tijd dat het laatste geldige VESC-packet is binnengekomen, in s",
    "Temperatuur van de VESC driver, in graden Celsius",
    "Temperatuur van de motor, in graden Celsius",
    "Motorstroom in A",
    "Ingangsstroom VESC, in A",
    "Huidige duty cycle, fractie tussen 0 en 1",
    "Huidige RPM van de motoras, in 1/min",
    "Ingangsspanning VESC",
    "Energie afgegeven door de VESC sinds boot, in Wh",
    "VESC foutcode",
    "Aantal gemiste startbytes in de VESC-communicatie",
    "Aantal keren dat de payload te groot was voor de buffer",
    "Aantal keren dat een END-byte onverwacht ontbrak",
    "Aantal gedetecteerde CRC-fouten",
    "Aantal onbekende packets",
    "Aantal keren dat er meer of minder velden dan verwacht in een packet zaten",
    "GPS longitude, in graden",
    "GPS latitude, in graden",
    "GPS direction",
    "GPS speed, in km/h",
    "GPS time, in seconden sinds het begin van de huidige GPS-week"
    ]   
    
    ACCU = [
    "Datalogger port",
    "Dataloggertijd, in s",
    "Format header",
    "Tijd sinds boot in seconden",
    "Tijd",
    "Datum",
    "Cel spanning van cel 1 in Volt",
    "Cel spanning van cel 2 in Volt",
    "Cel spanning van cel 3 in Volt",
    "Cel spanning van cel 4 in Volt",
    "Cel spanning van cel 5 in Volt",
    "Cel spanning van cel 6 in Volt",
    "Cel spanning van cel 7 in Volt",
    "Cel spanning van cel 8 in Volt",
    "Cel spanning van cel 9 in Volt",
    "Totale accu spanning in Volt",
    "Totale accu stroom in Ampère",
    "Totale accu stroom gefilterd in Ampère",
    "Huidige accu capaciteit in Ampère uur",
    "De gemeten capaciteit van de accu in Ampère uur",
    "Huidige percentage van accu",
    "Geschatte tijd totdat de accu leeg is in minuten",
    "Huidige accuvermogen, in Watt",
    "Totale energiebalans van de accu sinds boot, in Joule",
    "Onderspanning, één als er een fout opdeed",
    "Overspanning, één als er een fout opdeed",
    "Over temperatuur, één als er een fout opdeed",
    "Maximale delta spanning tussen de cellen in Volt",
    "Welke cel gebalanceerd wordt, 0 indien geen",
    "Als er gebalanceerd wordt, één als een cel wordt ontladen naar de rest van de accu",
    "Aantal oplaadpaden",
    "Aantal ontlaadpaden",
    "Laatste hardware fout type met tijd en datum",
    "Tijd laatste hardware fout",
    "Datum laatste hardware fout",
    "Temperatuur 1",
    "Temperatuur 2",
    "Temperatuur 3",
    "Temperatuur 4",
    "Temperatuur 5",
    "Temperatuur 6",
    "Huidige motorvermogen, in Watt",
    "Totale energiebalans van de motor sinds boot, in Joule",
    "Charge 0 spanning",
    "Charge 0 stroom",
    "Charge 1 spanning",
    "Charge 1 stroom",
    "Charge 2 spanning",
    "Charge 2 stroom",
    "Charge 3 spanning",
    "Charge 3 stroom",
    "Charge 4 spanning",
    "Charge 4 stroom",
    "Charge 5 spanning",
    "Charge 5 stroom",
    "Discharge 0 spanning",
    "Discharge 0 stroom",
    "Discharge 1 spanning",
    "Discharge 1 stroom",
    "I’m, welke accu ben ik",
    "“MEAS” als de accu-capaciteit momenteel wordt gemeten, anders leeg",
    "checksum"
    ]
    
    MPPT = [
        "Datalogger port",
        "Datalogger tijd, in s",
        "Format header",
        "MPPT-tijd, in s",
        "Paneel 1 ingangsspanning, in V",
        "Paneel 1 ingangsstroom, in I",
        "Paneel 1 instantaan ingangsvermogen, in W",
        "Paneel 1 totale ingangsenergie, in J",
        "Paneel 2 ingangsspanning, in V",
        "Paneel 2 ingangsstroom, in I",
        "Paneel 2 instantaan ingangsvermogen, in W",
        "Paneel 2 totale ingangsenergie, in J",
        "Uitgangsspanning, in V",
        "Kanaal 1 uitgangsstroom, in I",
        "Kanaal 2 uitgangsstroom, in I",
        "Kanaal 1 instantaan uitgangsvermogen, in W",
        "Kanaal 2 instantaan uitgangsvermogen, in W",
        "Kanaal 1 totale energie, in J",
        "Kanaal 2 totale energie, in J",
        "Paneel 1 temperatuur, in graden Celsius",
        "Paneel 2 temperatuur, in graden Celsius",
        "Kanaal 1 temperatuur (fets), in graden Celsius",
        "Kanaal 2 temperatuur (fets), in graden Celsius",
        "Extra sensor",
        "Kanaal 1 DAC waarde, in 12 bits",
        "Kanaal 2 DAC waarde, in 12 bits",
        "Algoritme mode",
        "Softwareversie",
        "Gps-longitude, in graden",
        "Gps-latitude, in graden",
        "GPS richting",
        "Gps-snelheid, in km/u",
        "Gps-tijd, in s",
        "Berekende zoninval pyranometer, in W/m2",
        "Ruwe meetwaarde pyranometer",
        "Checksum"
    ]

    MASTER = [
        "Datalogger port",
        "Dataloggertijd, in s",
        "Format header",
        "Cycle count",
        "Tijd",
        "Status",
        "Latitude",
        "Noord of Zuid",
        "Longitude",
        "Oost of West",
        "Snelheid over de grond in km/h",
        "Richting van de snelheid",
        "Datum",
        "Magnetische variatie",
        "Magnetische directie",
        "Mode indicator",
        "Data in balancers",
        "Snelheid ten opzichte van het water in Kilometers per uur",
        "Board Temperatuur"
    ]



    
